apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      nodeSelector:
        kubernetes.io/hostname: {{ .Values.nodeSelector.hostname }}
      containers:
        - name: {{ .Release.Name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: APPLICATION_PORT
              valueFrom:
                configMapKeyRef:
                  name: investment-service-config
                  key: APPLICATION_PORT
            - name: SWAGGER_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: investment-service-config
                  key: SWAGGER_SERVER_URL
            - name: DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: investment-service-config
                  key: DATABASE_HOST
            - name: DATABASE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: investment-service-config
                  key: DATABASE_USERNAME
            - name: DATABASE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: investment-service-config
                  key: DATABASE_PASSWORD
            - name: DEV_KAFKA_BOOTSTRAP_SERVER
              valueFrom:
                configMapKeyRef:
                  name: investment-service-config
                  key: DEV_KAFKA_BOOTSTRAP_SERVER
            - name: PROD_KAFKA_BOOTSTRAP_SERVER
              valueFrom:
                configMapKeyRef:
                  name: investment-service-config
                  key: PROD_KAFKA_BOOTSTRAP_SERVER
            - name: KAFKA_BOOTSTRAP_PORT
              valueFrom:
                configMapKeyRef:
                  name: investment-service-config
                  key: KAFKA_BOOTSTRAP_PORT
            - name: OPENAI_API_KEY
              valueFrom:
                configMapKeyRef:
                  name: investment-service-config
                  key: OPENAI_API_KEY
            - name: WEBCLIENT_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: investment-service-config
                  key: WEBCLIENT_BASE_URL
