apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway-service
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  
  source:
    repoURL: https://github.com/FLEX-CODEPING/FLEX-GitOps.git
    targetRevision: main
    path: charts/gateway-service
  
  destination:
    server: https://kubernetes.default.svc
    namespace: gateway-service
  
  syncPolicy:
    automated: 
      prune: true 
      selfHeal: true   
    syncOptions:
      - 'CreateNamespace=true'
